[tool.pyright]
analyzeUnannotatedFunctions = false
strictParameterNoneValue = false
enableTypeIgnoreComments = false
disableBytesTypePromotions = false
strictListInference = false
strictDictionaryInference = false
strictSetInference = false
deprecateTypingAliases = false
enableExperimentalFeatures = false
reportMissingModuleSource = false
reportMissingImports = false
reportUndefinedVariable = false
reportAssertAlwaysTrue = false
reportInvalidStringEscapeSequence = false
reportInvalidTypeVarUse = false
reportMissingTypeStubs = false
reportSelfClsParameterName = false
reportUnsupportedDunderAll = false
reportUnusedExpression = false
reportWildcardImportFromLibrary = false
reportGeneralTypeIssues = false
reportOptionalSubscript = false
reportOptionalMemberAccess = false
reportOptionalCall = false
reportOptionalIterable = false
reportOptionalContextManager = false
reportOptionalOperand = false
reportTypedDictNotRequiredAccess = false
reportPrivateImportUsage = false
reportUnboundVariable = false
reportUnusedCoroutine = false
reportFunctionMemberAccess = false
reportIncompatibleMethodOverride = false
reportIncompatibleVariableOverride = false
reportOverlappingOverload = false
reportConstantRedefinition = false
reportDeprecated = false
reportDuplicateImport = false
reportIncompleteStub = false
reportInconsistentConstructor = false
reportInvalidStubStatement = false
reportMatchNotExhaustive = false
reportMissingParameterType = false
reportMissingTypeArgument = false
reportPrivateUsage = false
reportTypeCommentUsage = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnnecessaryCast = false
reportUnnecessaryComparison = false
reportUnnecessaryContains = false
reportUnnecessaryIsInstance = false
reportUnusedClass = false
reportUnusedImport = false
reportUnusedFunction = false
reportUnusedVariable = false
reportUntypedBaseClass = false
reportUntypedClassDecorator = false
reportUntypedFunctionDecorator = false
reportUntypedNamedTuple = false
reportCallInDefaultInitializer = false
reportImplicitOverride = false
reportImplicitStringConcatenation = false
reportImportCycles = false
reportMissingSuperCall = false
reportPropertyTypeMismatch = false

pythonVersion = "3.11"
